// Daftar tag type per tahap — dipakai bareng oleh SurveyFormPage.tsx (isi
// form) & SurveyReportSummary.tsx (tampilan "Survey Selesai") supaya kedua
// tempat itu query tag yang persis sama, tidak ada 2 sumber yang bisa beda.
import { TAG_TYPES } from '$lib/constants/tag';

export const STAGE1_TAG_TYPES: string[] = [
	TAG_TYPES.SUN_EXPOSURE_OBSTRUCTION,
	TAG_TYPES.DRAINAGE,
	TAG_TYPES.WATER_SOURCE,
	TAG_TYPES.ELECTRICITY_SOURCE,
	TAG_TYPES.ENTRANCE_ACCESS,
	TAG_TYPES.GARDEN_ENTRANCE_ACCESS,
	TAG_TYPES.GROUND_SURFACE_CONDITION,
	TAG_TYPES.LAND_PREPARATION,
	TAG_TYPES.SOIL_MOISTURE,
	TAG_TYPES.SOIL_PLANTING_READINESS
];

export const STAGE2_TAG_TYPES: string[] = [
	TAG_TYPES.GARDEN_FACING_DIRECTION,
	TAG_TYPES.AREA_SUN_EXPOSURE,
	TAG_TYPES.RAIN_GUTTER_NEED,
	TAG_TYPES.CHILDREN_PRESENCE,
	TAG_TYPES.ANIMAL_PRESENCE,
	TAG_TYPES.CARE_LEVEL,
	TAG_TYPES.SPECIAL_AREA,
	TAG_TYPES.GARDEN_THEME,
	TAG_TYPES.FIXED_STRUCTURE
];
